version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:227000603860:task-definition/TD-2025:6"
        LoadBalancerInfo:
          ContainerName: "boot3"
          ContainerPort: 9080