version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment

hooks:
  BeforeInstall:
    - location: /bin/bash
      timeout: 300
      runas: root
      script: |
        echo "Listing contents :"
        ls -ltr
    - location: scripts/stop-container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start-container.sh
      timeout: 300
      runas: root
