version: 0.0
os: linux
# Test
files:
  - source: /
    destination: /home/ec2-user/deployment

hooks:
  BeforeInstall:
    - location: scripts/pull-ecr-image.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start-container.sh
      timeout: 300
      runas: root
