name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  applicationfolder: Boot3WarWeb
  AWS_REGION: us-east-2
  S3BUCKET: cogitosum-boot3warweb-ohio


jobs:
  build:
    name: Build - Package - Dockerize
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Setup the configuration
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: chmod
        run: chmod -R +x ./.github
      # Build the code ( Maven )
      - name: Build and Package Maven
        id: package
        working-directory: .
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh
      # Step Upload to S3
      - name: Upload Artifact to s3
        working-directory: ./target
        run: aws s3 cp ./*.war s3://${{ env.S3BUCKET }}/
      # Step Trigger CodeBuild
      - name: Trigger AWS CodeBuild
        run: |
          aws codebuild start-build --project-name Boot3WarWeb
      # Step Trigger CodeDeploy
      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment --application-name boot3warweb --deployment-group-name boot3warweb2025 --revision file://imagedefinitions.json


